[package]
name = "adaptor-faest"
version = "0.1.0"
edition = "2024"

[dependencies]
faest = { git = "https://github.com/kc1212/faest-rs.git", rev = "15bb4de774959161c11534d67244f8da41506034" }
generic-array = { version = "1", features = ["alloc"] }
rand = { version = "0.8" }

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "adaptor"
harness = false
