[package]
name = "adaptor-faest"
version = "0.1.0"
edition = "2024"

[dependencies]
# faest = { git = "https://github.com/kc1212/faest-rs.git", branch = "kc1212/expose-api-for-adaptor-sig" }
faest = { path = "../faest-rs" }
generic-array = { version = "1", features = ["alloc"] }
rand = { version = "0.8" }

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "adaptor"
harness = false
