[package]
name = "adaptor-faest"
version = "0.1.0"
edition = "2024"

[dependencies]
faest = { git = "https://github.com/kc1212/faest-rs.git", rev = "6d8ccb2c42de4b99b67fe8e14c448ff67f7ef836" }
generic-array = { version = "1", features = ["alloc"] }
rand = { version = "0.8" }

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "adaptor"
harness = false
